Add OP_MULPOW2.
cashweb/cashd pull request #103
Opened 2021-03-21 22:14 UTC by EyeOfPython

This computes x n -> x * 2^n, which is useful for many applications.

2021-03-21 22:29 UTC, schancel commented on src/script/interpreter.cpp
> -        case OP_RSHIFT:
Why's this going away?

2021-03-21 22:29 UTC, schancel commented on src/script/interpreter.cpp
> -        case OP_RSHIFT:
Nevermind

2021-03-21 22:33 UTC, EyeOfPython commented on src/script/interpreter.cpp
> -        case OP_RSHIFT:
😉

2021-03-21 22:51 UTC, schancel requested changes

2021-03-21 22:51 UTC, schancel commented on src/script/script.h
> +            return CScriptNum(0);
You can move this up first. Saves two branches in this case.

2021-03-21 22:51 UTC, schancel commented on src/script/script.h
> +        const uint64_t absval = m_value > 0 ? m_value : -m_value;
Should note that this is defined as `x` for reference below.

2021-03-21 23:20 UTC, schancel requested changes

2021-03-21 23:20 UTC, schancel commented on src/test/op_mulpow2_tests.cpp
> +static bool Pow2(int64_t base, int64_t exponent, int64_t &result) {
I would consider using the existing pow math functions. But this also works.

2021-03-28 19:27 UTC, schancel approved these changes

2021-03-28 19:29 UTC, merged